#!/bin/bash

# Variables
URL="https://downloads.sourceforge.net/libtirpc/libtirpc-1.3.5.tar.bz2"
VERSION="1.3.5"
MD5SUM="59a5aba60d99621963d0109f95b622f2"

# Download the package
curl -O $URL

# Verify the download by checking the MD5 sum
echo "$MD5SUM libtirpc-$VERSION.tar.bz2" | md5sum -c -

# If the MD5 sum does not match, exit the script
if [ $? -ne 0 ]; then
  echo "MD5 checksum does not match. Exiting."
  exit 1
fi

# Extract the downloaded tarball
tar -xvf libtirpc-$VERSION.tar.bz2

# Change to the extracted directory
cd libtirpc-$VERSION

# Configure the package
./configure --prefix=/usr                                   \
            --sysconfdir=/etc                               \
            --disable-static                                \
            --disable-gssapi

# Build the package
make

# Install the package as the root user
sudo make install

# Cleanup
cd ..
rm -rf libtirpc-$VERSION libtirpc-$VERSION.tar.bz2

echo "libtirpc-$VERSION installation is complete."
