services:
  nginx:
    image: nginx:1.27-alpine-slim
    container_name: my-nginx-container
    volumes:
      - C:\Users\dmusa\nginx\config\nginx.conf:/etc/nginx/nginx.conf:ro
      - C:\Users\dmusa\Downloads\media:/mnt/media:ro
    ports:
      - "8088:80"
    restart: always
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - NGINX_VERSION=1.27.0
      - PKG_RELEASE=1
    labels:
      maintainer: "NGINX Docker Maintainers <docker-maint@nginx.com>"
    networks:
      - bridge

networks:
  bridge:
    driver: bridge
