version: '3.7'

services:
  transmission:
    image: transmission:latest  # Use built image with Podman
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /media/config/transmission:/etc/transmission-daemon
      - /media/downloads:/var/lib/transmission-daemon/downloads
      - /media/watch:/var/lib/transmission-daemon/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
